import os
import sqlite3
from bs4 import BeautifulSoup
import re
from datetime import datetime

def run_task():
    """
    This task parses seismic data from the locally saved HTML file (lista_de_sismos.html)
    and stores it in a SQLite database, avoiding duplicate entries.
    """
    db_path = os.path.join(os.path.dirname(__file__), '..', 'sismos.db')
    # Path to the local file generated by the download task
    local_html_path = os.path.join(os.path.dirname(__file__), '..', 'lista_de_sismos.html')

    print(f"    - Parsing local file: {local_html_path}")

    try:
        # 1. Initialize Database
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()
        cursor.execute("""
        CREATE TABLE IF NOT EXISTS terremotos (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            fecha TEXT,
            hora TEXT,
            latitud REAL,
            longitud REAL,
            profundidad_km REAL,
            magnitud_richter REAL,
            region TEXT,
            UNIQUE(fecha, hora, latitud, longitud)
        )
        """)
        conn.commit()
        conn.close()
        print("    - Database initialized successfully.")

        # 2. Read and parse the local file
        with open(local_html_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        soup = BeautifulSoup(content, 'html.parser')
        
        pre_tags = soup.find_all('pre')
        
        if not pre_tags:
            print("    [!] No <pre> tags found in the HTML file. It might be empty or the structure changed.")
            return

        # Re-connect to DB for insertion
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()
        
        new_records_count = 0
        
        for pre in pre_tags:
            # Get the full text from the <pre> tag
            full_text = pre.get_text().strip()
            
            # Split the text into parts based on multiple spaces
            parts = re.split(r'\s+', full_text)
            
            # Check if there are enough parts to form a complete record
            if len(parts) > 7:
                # Convert date from YY/MM/DD to YYYY-MM-DD
                fecha_obj = datetime.strptime(parts[0], '%y/%m/%d')
                fecha = fecha_obj.strftime('%Y-%m-%d')
                hora = parts[1]
                lat = float(parts[2])
                lon = float(parts[3])
                prof = float(parts[4])
                mag = float(parts[5])
                # The region is formed by the rest of the parts, skipping the 7th part which is the letter 'C'
                region = ' '.join(parts[7:])
                
                # Insert the new record into the database
                cursor.execute("""
                INSERT OR IGNORE INTO terremotos (fecha, hora, latitud, longitud, profundidad_km, magnitud_richter, region)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """, (fecha, hora, lat, lon, prof, mag, region))
                
                if cursor.rowcount > 0:
                    new_records_count += 1

        conn.commit()
        conn.close()
        
        if new_records_count > 0:
            print(f"    - Success! Added {new_records_count} new seismic records from the local file.")
        else:
            print("    - No new seismic records found in the local file to add.")
            
        print("    - Task 'parse_sismos_file' finished.")

    except FileNotFoundError:
        print(f"    [!] Error: The file was not found at {local_html_path}. Make sure the download task ran first.")
    except sqlite3.Error as e:
        print(f"    [!] Database error: {e}")
    except Exception as e:
        print(f"    [!] An unexpected error occurred: {e}")


